using System.Security.Cryptography;
using System.Text.RegularExpressions;
using VaultSharp;
using VaultSharp.V1.AuthMethods.AppRole;
using VaultSharp.V1.AuthMethods.Token;

namespace ModelContextGateway.Infrastructure.Secrets
{
    public enum MasterKeySource
    {
        External,
        Vault,
        SecretFile,
        Configured,
        AutoGenerated
    }

    public static class DbKeyHelper
    {
        private static string? _cachedKey;
        private static readonly object _lock = new object();
        private static Func<IVaultClient>? _vaultClientFactory;

        public static MasterKeySource ActiveKeySource { get; set; } = MasterKeySource.AutoGenerated;

        public static void SetVaultClientFactory(Func<IVaultClient>? factory)
        {
            lock (_lock)
            {
                _vaultClientFactory = factory;
            }
        }

        public static void SetCachedKey(string key, MasterKeySource source = MasterKeySource.Configured)
        {
            lock (_lock)
            {
                _cachedKey = key;
                ActiveKeySource = source;
            }
        }

        public static string ResolveDbEncryptionKey(IConfiguration configuration, ILogger? logger = null)
        {
            if (_cachedKey != null)
            {
                return _cachedKey;
            }

            lock (_lock)
            {
                if (_cachedKey != null)
                {
                    return _cachedKey;
                }

                // 1. HashiCorp Vault Bootstrapping (if VAULT_ADDR or Vault:Address is configured or factory is set)
                var vaultAddress = configuration["Vault:Address"]
                    ?? configuration["MCG_VAULT_ADDR"]
                    ?? configuration["VAULT_ADDR"]
                    ?? Environment.GetEnvironmentVariable("MCG_VAULT_ADDR")
                    ?? Environment.GetEnvironmentVariable("VAULT_ADDR");

                if (!string.IsNullOrWhiteSpace(vaultAddress) || _vaultClientFactory != null)
                {
                    var vaultKey = RetrieveVaultMasterKey(configuration, vaultAddress);
                    if (!string.IsNullOrWhiteSpace(vaultKey))
                    {
                        _cachedKey = vaultKey;
                        ActiveKeySource = MasterKeySource.Vault;
                        return _cachedKey;
                    }
                }

                // 2. Direct Environment / Config Variables
                var key = configuration["MCG_MASTER_KEY"]
                    ?? configuration["MCG_SECRET"]
                    ?? configuration["DB_ENCRYPTION_KEY"]
                    ?? Environment.GetEnvironmentVariable("MCG_MASTER_KEY")
                    ?? Environment.GetEnvironmentVariable("MCG_SECRET")
                    ?? Environment.GetEnvironmentVariable("DB_ENCRYPTION_KEY");

                if (!string.IsNullOrWhiteSpace(key))
                {
                    _cachedKey = key.Trim();
                    ActiveKeySource = MasterKeySource.External;
                    return _cachedKey;
                }

                // 3. Explicit File Path from Environment / Config (Docker / K8s file secrets)
                var filePath = configuration["MCG_MASTER_KEY_FILE"]
                    ?? configuration["MCG_SECRET_FILE"]
                    ?? configuration["DB_ENCRYPTION_KEY_FILE"]
                    ?? Environment.GetEnvironmentVariable("MCG_MASTER_KEY_FILE")
                    ?? Environment.GetEnvironmentVariable("MCG_SECRET_FILE")
                    ?? Environment.GetEnvironmentVariable("DB_ENCRYPTION_KEY_FILE");

                if (!string.IsNullOrWhiteSpace(filePath) && File.Exists(filePath))
                {
                    var fileSecret = File.ReadAllText(filePath).Trim();
                    if (!string.IsNullOrWhiteSpace(fileSecret))
                    {
                        _cachedKey = fileSecret;
                        ActiveKeySource = MasterKeySource.SecretFile;
                        return _cachedKey;
                    }
                }

                // 4. Standard Docker / Kubernetes Secrets Default Paths
                var defaultDockerSecretPaths = new[]
                {
                    "/run/secrets/mcg_master_key",
                    "/run/secrets/mcg_secret",
                    "/run/secrets/router_master_key",
                    "/run/secrets/router_secret",
                    "/run/secrets/master_key"
                };

                foreach (var dPath in defaultDockerSecretPaths)
                {
                    if (File.Exists(dPath))
                    {
                        var dSecret = File.ReadAllText(dPath).Trim();
                        if (!string.IsNullOrWhiteSpace(dSecret))
                        {
                            _cachedKey = dSecret;
                            ActiveKeySource = MasterKeySource.SecretFile;
                            return _cachedKey;
                        }
                    }
                }

                // 5. Persistent Keyfile in Data Directory (./data/.master.key)
                string dataDir = ResolveDataDirectory(configuration);
                var keyFilePath = Path.Combine(dataDir, ".master.key");

                if (File.Exists(keyFilePath))
                {
                    var existingKey = File.ReadAllText(keyFilePath).Trim();
                    if (!string.IsNullOrWhiteSpace(existingKey))
                    {
                        _cachedKey = existingKey;
                        ActiveKeySource = MasterKeySource.Configured;
                        return _cachedKey;
                    }
                }

                // 6. Auto-Generate and Persist to Keyfile
                try
                {
                    Directory.CreateDirectory(dataDir);
                    var newKeyBytes = RandomNumberGenerator.GetBytes(32);
                    var newKey = Convert.ToBase64String(newKeyBytes);

                    File.WriteAllText(keyFilePath, newKey);

                    // Apply strict POSIX permissions (0600) on Linux/macOS if supported
                    if (!OperatingSystem.IsWindows())
                    {
                        try
                        {
                            File.SetUnixFileMode(keyFilePath, UnixFileMode.UserRead | UnixFileMode.UserWrite);
                        }
                        catch
                        {
                            // Ignored on file systems without POSIX permissions support
                        }
                    }

                    if (logger != null)
                    {
                        logger.LogWarning("[SECURITY] Auto-generated persistent master encryption key saved to '{KeyFilePath}'.", keyFilePath);
                        logger.LogWarning("[SECURITY] Backup this key to ensure recoverable access to encrypted credentials across storage re-provisioning.");
                    }

                    _cachedKey = newKey;
                    ActiveKeySource = MasterKeySource.AutoGenerated;
                    return _cachedKey;
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException(
                        $"FATAL: Master encryption key is missing and failed to persist auto-generated key to '{keyFilePath}'. " +
                        "Ensure the data directory is writable or configure 'MCG_MASTER_KEY' or key file.", ex);
                }
            }
        }

        private static string? RetrieveVaultMasterKey(IConfiguration configuration, string? address)
        {
            IVaultClient? client = null;
            if (_vaultClientFactory != null)
            {
                client = _vaultClientFactory();
            }
            else
            {
                if (string.IsNullOrWhiteSpace(address))
                {
                    return null;
                }

                if (!address.StartsWith("https://", StringComparison.OrdinalIgnoreCase) && !address.StartsWith("http://", StringComparison.OrdinalIgnoreCase))
                {
                    throw new ArgumentException("Vault Address must use the HTTP or HTTPS scheme.");
                }

                var roleId = configuration["Vault:RoleId"] ?? configuration["MCG_VAULT_ROLE_ID"] ?? configuration["VAULT_ROLE_ID"] ?? Environment.GetEnvironmentVariable("MCG_VAULT_ROLE_ID") ?? Environment.GetEnvironmentVariable("VAULT_ROLE_ID");
                var secretId = configuration["Vault:SecretId"] ?? configuration["MCG_VAULT_SECRET_ID"] ?? configuration["VAULT_SECRET_ID"] ?? Environment.GetEnvironmentVariable("MCG_VAULT_SECRET_ID") ?? Environment.GetEnvironmentVariable("VAULT_SECRET_ID");
                var token = configuration["Vault:Token"] ?? configuration["MCG_VAULT_TOKEN"] ?? configuration["VAULT_TOKEN"] ?? Environment.GetEnvironmentVariable("MCG_VAULT_TOKEN") ?? Environment.GetEnvironmentVariable("VAULT_TOKEN");

                VaultSharp.V1.AuthMethods.IAuthMethodInfo authMethod;
                if (!string.IsNullOrEmpty(roleId) && !string.IsNullOrEmpty(secretId))
                {
                    authMethod = new AppRoleAuthMethodInfo(roleId, secretId);
                }
                else if (!string.IsNullOrEmpty(token))
                {
                    authMethod = new TokenAuthMethodInfo(token);
                }
                else
                {
                    return null;
                }

                var settings = new VaultClientSettings(address, authMethod);
                client = new VaultClient(settings);
            }

            if (client == null)
            {
                return null;
            }

            var vaultPath = configuration["MCG_VAULT_MASTER_KEY_PATH"] ?? configuration["VAULT_MASTER_KEY_PATH"] ?? configuration["Vault:MasterKeyPath"] ?? "mcg/master-key";
            var mountPoint = configuration["MCG_VAULT_MOUNT_POINT"] ?? configuration["VAULT_MOUNT_POINT"] ?? configuration["Vault:MountPoint"] ?? "secret";
            if (vaultPath.Contains(':'))
            {
                var parts = vaultPath.Split(':', 2);
                mountPoint = parts[0];
                vaultPath = parts[1];
            }

            var keyName = configuration["MCG_VAULT_MASTER_KEY_NAME"] ?? configuration["VAULT_MASTER_KEY_NAME"] ?? configuration["Vault:MasterKeyName"] ?? "master_key";

            try
            {
                var secretData = client.V1.Secrets.KeyValue.V2.ReadSecretAsync(path: vaultPath, mountPoint: mountPoint).GetAwaiter().GetResult();
                if (secretData?.Data?.Data != null)
                {
                    if (secretData.Data.Data.TryGetValue(keyName, out var val) && val != null)
                    {
                        return val.ToString()?.Trim();
                    }

                    foreach (var fallback in new[] { "master_key", "master-key", "key", "value", "secret" })
                    {
                        if (secretData.Data.Data.TryGetValue(fallback, out var fVal) && fVal != null)
                        {
                            return fVal.ToString()?.Trim();
                        }
                    }

                    if (secretData.Data.Data.Count == 1)
                    {
                        var singleVal = secretData.Data.Data.Values.FirstOrDefault();
                        if (singleVal != null)
                        {
                            return singleVal.ToString()?.Trim();
                        }
                    }
                }

                return null;
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException($"Failed to retrieve master encryption key from Vault at '{address ?? "configured factory"}' path '{mountPoint}:{vaultPath}'.", ex);
            }
        }

        public static string ResolveDataDirectory(IConfiguration configuration)
        {
            var customDataDir = configuration["MCG_DATA_DIR"]
                ?? configuration["DATA_DIR"]
                ?? configuration["DataDir"]
                ?? Environment.GetEnvironmentVariable("MCG_DATA_DIR")
                ?? Environment.GetEnvironmentVariable("DATA_DIR");

            if (!string.IsNullOrWhiteSpace(customDataDir))
            {
                return Path.GetFullPath(customDataDir);
            }

            var explicitDbPath = configuration["MCG_DB_PATH"]
                ?? configuration["MCG_DATABASE_PATH"]
                ?? configuration["DATABASE_PATH"]
                ?? Environment.GetEnvironmentVariable("MCG_DB_PATH")
                ?? Environment.GetEnvironmentVariable("MCG_DATABASE_PATH");

            if (!string.IsNullOrWhiteSpace(explicitDbPath))
            {
                var dir = Path.GetDirectoryName(explicitDbPath);
                if (!string.IsNullOrWhiteSpace(dir))
                {
                    return Path.GetFullPath(dir);
                }
            }

            var connStr = configuration.GetConnectionString("DefaultConnection")
                ?? configuration.GetConnectionString("Sqlite")
                ?? configuration["ConnectionStrings:DefaultConnection"]
                ?? configuration["ConnectionStrings:Sqlite"];

            if (!string.IsNullOrWhiteSpace(connStr) && connStr.Contains("Data Source=", StringComparison.OrdinalIgnoreCase))
            {
                var match = Regex.Match(connStr, @"Data Source=([^;]+)", RegexOptions.IgnoreCase);
                if (match.Success && !match.Groups[1].Value.StartsWith("file:", StringComparison.OrdinalIgnoreCase))
                {
                    var sqliteFile = match.Groups[1].Value.Trim();
                    var dir = Path.GetDirectoryName(sqliteFile);
                    if (!string.IsNullOrWhiteSpace(dir))
                    {
                        return Path.GetFullPath(dir);
                    }
                }
            }

            return Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "data");
        }

        public static void ResetCache()
        {
            lock (_lock)
            {
                _cachedKey = null;
                ActiveKeySource = MasterKeySource.AutoGenerated;
                _vaultClientFactory = null;
            }
        }
    }
}
